["RegularGrid"]
"n"=2
"Î³"=5

["Î©"]
type="ReproducingKernel{:Linear2D,:â—‹,:CubicSpline,:Vor2}"
"ğ“’".tag="Î©"
"ğ“–".type="Vor2"
"ğ“–"."ğ­"="âˆ‡â‚‚ğ­"

["Î“áµ—"]
type="ReproducingKernel{:Linear2D,:â—‹,:CubicSpline,:Seg2}"
"ğ“’".tag="Î“áµ—"
"ğ“–".type="SegGI2"
"ğ“–"."ğ­"="ğ­"
"ğ“–"."normal"=true

["Î“áµ"]
type="ReproducingKernel{:Linear2D,:â—‹,:CubicSpline,:Seg2}"
"ğ“’".tag="Î“áµ"
"ğ“–".type="SegGI2"
"ğ“–"."ğ­"="âˆ‡â‚‚ğ­"
"ğ“–"."normal"=true